.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ARC_BE2LE 1 "November 19, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
arc_be2le \- program to convert Weatherlink WLK files from big endian to little endian
.SH SYNOPSIS
.B arc_be2le
.RI source_directory dest_directory
.br
.SH DESCRIPTION
This manual page describes the use of
.B arc_be2le
.
It converts wview archive data in source_directory from big endian
to little endian then stores the result in dest_directory.
.SH OPTIONS
There are no options and source_directory and dest_directory are mandatory.
.TP
.SH SEE ALSO
.BR arc_le2be (1),
.BR wlk2sqlite (1),
.BR sqlite2wlk (1).
.BR /usr/share/doc/wview/wview-User-Manual.html
.br
.SH AUTHOR
arc_be2le was written by Mark Teel.
.PP
This manual page was written by Mark Teel <mteel2005@gmail.com>,
for the Debian project (and may be used by others).
