.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH WVIEWHTMLCONFIG 1 "November 19, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
wviewhtmlconfig \- script to configure the HTML templates for a wview installation
.SH SYNOPSIS
.B wviewhtmlconfig
.RI
.br
.SH DESCRIPTION
This manual page describes the use of
.B wviewhtmlconfig
.
Configure a wview installation's HTML templates.
.BR
.BR Note: wviewconfig MUST be run before this script.
.BR Note: must be executed on the source wview server.
.SH OPTIONS
There are no options.
.TP
.SH SEE ALSO
.BR wviewconfig (1),
.BR /usr/share/doc/wview/wview-User-Manual.html
.br
.SH AUTHOR
wviewhtmlconfig was written by Mark Teel.
.PP
This manual page was written by Mark Teel <mteel2005@gmail.com>,
for the Debian project (and may be used by others).
